### ISSUE TITLE
AzirQ

### ISSUE THREAD

**Issue by D3ftsu** [soulcaliber/LeagueSharp#17]
ChampionName = "Azir"
SpellName = "AzirQWrapper"
FromObjects = {"AzirSoldier"}

startPos = obj.Position and args.End is fine for endPos
https://i.gyazo.com/69447d82a968dfd5494f6fb0f225cf3b.gif

**Comment by xKurisu** [comment]
Hey mayomie uses an object tracker to track these kind of things but it currently only works with one object and wont work with multiple soldiers.

**Comment by D3ftsu** [comment]
yes but he can still add this to normal ProcessSpell detection, i can't see azir spelldata anywhere

**Comment by xKurisu** [comment]
Added.
